/**
 * Virtual product grouping for the Saudade Voces art shop.
 *
 * Shopify currently stores each (painting × material) as a separate product
 * (e.g. "Soul Gathering — Canvas", "Soul Gathering — Framed Poster"). We want
 * the storefront to show ONE master product per painting, with variants on
 * Material × Frame × Size. This module synthesises those master products
 * client-side from the raw Shopify list — no Shopify import needed.
 *
 * The synthesised "virtual" products preserve the real Shopify variant IDs,
 * so AddToCart / checkout continues to work unchanged.
 *
 * Decisions baked in (per Maya, 2026-04-25):
 * - Master title = canonical painting name (no " — Material" suffix).
 * - Variant axes: Material × Frame × Size.
 * - "Assembly: Not assembled" Framed Poster variants are dropped; framed
 *   items default to Ready-to-hang.
 * - "Nawra" is "Narwa" misspelt; merged.
 * - Orientation (Vertical/Horizontal) is folded into Size as a prefix.
 * - Non-art products (clothing, etc.) pass through untouched.
 */

import type {
  ShopifyImage,
  ShopifyProduct,
  ShopifyProductVariant,
  ShopifySelectedOption,
} from "./shopify";
import productPaintingMap from "./productPaintingMap.json";
import paintingPalette from "./paintingPalette.json";
import { translateOptionValue } from "./optionTranslations";

/**
 * Source-of-truth map: { shopifyHandle: { painting: "Canonical Name", ... } }
 * Generated by `build_painting_map.py` (see Shopify Products workspace folder)
 * from perceptual-hashed image matching against the canonical paintings in
 * `mockup_scripts/published art/`. Used to fix mistitled Shopify products.
 */
type PaintingMapEntry = { painting: string; confidence?: string };
const PAINTING_MAP = productPaintingMap as Record<string, PaintingMapEntry>;

/** Per-painting palette classification ("bw" | "color"). Loaded from
 *  paintingPalette.json. Surfaced to the storefront as a tag like
 *  "palette:bw" / "palette:color" so the shop sidebar can filter by it. */
const PALETTE_MAP = paintingPalette as Record<string, string>;
export type PaintingPalette = "bw" | "color";
export function getPaintingPalette(painting: string): PaintingPalette | null {
  const v = PALETTE_MAP[painting];
  return v === "bw" || v === "color" ? v : null;
}
export const PALETTE_TAG_PREFIX = "palette:";

// ---------- Configuration ----------

const MATERIALS = ["Poster", "Framed Poster", "Canvas", "Framed Canvas"] as const;
type Material = (typeof MATERIALS)[number];

/** Canonical painting names → spellings that should be folded into them. */
const TITLE_ALIASES: Record<string, string> = {
  Nawra: "Narwa",
  Interwined: "Intertwined",
};

// Names of variant options as they appear in the source Shopify products.
const OPTION_SIZE = "Size";
const OPTION_FRAME = "Frame";
const OPTION_ASSEMBLY = "Assembly";
const OPTION_ORIENTATION = "Orientation";

/**
 * Localised aliases for variant option NAMES (not values). Shopify Markets
 * translates option names per locale, so a Spanish variant has option name
 * "Marco" instead of "Frame" and "Tamaño" instead of "Size". Without this
 * table, findOption() falls back to "None"/"Default" on every non-English
 * detail page — exactly the symptom Maya hit when ES/PT pages stopped
 * showing frame and size pickers. Lower-cased lookup. */
const OPTION_NAME_ALIASES: Record<string, string[]> = {
  [OPTION_SIZE]: [
    "size",
    "tamaño", "tamano",            // ES (with/without diacritic)
    "tamanho",                      // PT
    "rozmiar",                      // PL
  ],
  [OPTION_FRAME]: [
    "frame",
    "marco",                        // ES
    "moldura",                      // PT
    "rama", "ramka",                // PL
  ],
  [OPTION_ASSEMBLY]: [
    "assembly",
    "ensamblaje", "montaje",        // ES
    "montagem",                     // PT
    "montaż", "montaz",             // PL
  ],
  [OPTION_ORIENTATION]: [
    "orientation",
    "orientación", "orientacion",   // ES
    "orientação", "orientacao",     // PT
    "orientacja",                   // PL
  ],
};

// Names of variant options on the synthesised master product.
const OUT_MATERIAL = "Material";
const OUT_FRAME = "Frame";
const OUT_SIZE = "Size";

// ---------- Helpers ----------

/** Parse "Painting Name — Material" → { painting, material }. Locale-aware:
 *  the material token can be any known translation (English / Spanish /
 *  Portuguese / Polish), so titles like "A Cerimônia — Tela Emoldurada" or
 *  "La Ceremonia — Póster Enmarcado" parse correctly.
 *
 *  Falls back to a separator-less suffix match for titles like "Narwa Premium
 *  Matte Paper" (no dash) — common when products come from Gelato/Printful
 *  integrations that name SKUs after the print medium without punctuation. */
function parseTitle(title: string): { painting: string; material: Material } | null {
  const trimmed = title.trim();

  // Step 1 — explicit dash separator (em / en / hyphen).
  const m = trimmed.match(/^(.*?)\s+[—–-]\s+(.+?)\s*$/);
  if (m) {
    const rawMaterial = m[2].trim();
    const localised = normaliseMaterial(rawMaterial);
    if (localised) return { painting: m[1].trim(), material: localised };
    if ((MATERIALS as readonly string[]).includes(rawMaterial)) {
      return { painting: m[1].trim(), material: rawMaterial as Material };
    }
  }

  // Step 2 — no separator, but the end of the title matches a known material
  // alias. Tries longest aliases first so "Framed Premium Matte Paper" wins
  // before "Premium Matte Paper" and "Matte Paper".
  const lower = trimmed.toLowerCase();
  const aliases = Object.keys(MATERIAL_ALIASES_I18N).sort(
    (a, b) => b.length - a.length,
  );
  for (const alias of aliases) {
    if (lower.endsWith(alias)) {
      const material = MATERIAL_ALIASES_I18N[alias];
      const cut = trimmed.length - alias.length;
      const painting = trimmed.slice(0, cut).replace(/[\s—–\-:|·]+$/, "").trim();
      if (painting) return { painting, material };
    }
  }

  return null;
}

function canonicalize(painting: string): string {
  return TITLE_ALIASES[painting] ?? painting;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function findOption(opts: ShopifySelectedOption[], name: string): string | undefined {
  // Case-insensitive name match across every known locale alias for `name`.
  // Shopify translates option names ("Frame"→"Marco"/"Moldura"), so the
  // English string by itself is not enough on ES/PT/PL detail pages.
  const aliases = OPTION_NAME_ALIASES[name] ?? [name.toLowerCase()];
  return opts.find((o) => aliases.includes(o.name.toLowerCase()))?.value;
}

// Patterns that strongly suggest a given option is Frame / Size, used as
// VALUE-based fallbacks when the option's name is non-standard. Conservative
// on purpose — false positives would cause Material/Orientation/Assembly to
// be misclassified.
const FRAME_NAME_RE = /frame|marco|moldura|rama|ramka/i;
const FRAME_VALUE_RE =
  /\b(frame|marco|moldura|rama|black|white|wood|dark wood|negro|negra|blanco|madera|preto|preta|branco|branca|madeira|czarn|biał|biala|drewn)/i;
const SIZE_NAME_RE = /size|tamañ|tamano|tamanh|rozmiar|measur|medid|wymiar|format/i;
const SIZE_VALUE_RE = /\d+\s*[x×]\s*\d+|\d+\s*(?:cm|mm|in|inch|"|″)\b/i;
const ORIENT_NAME_RE = /orient/i;
const ORIENT_VALUE_RE = /\b(vertical|horizontal|pionow|poziom|vertik|horizont)/i;

/** Find the variant's frame value robustly:
 *  1) by the option named "Frame" (any locale alias);
 *  2) failing that, by any option NAME that hits the frame keyword regex;
 *  3) failing that, by any option VALUE that looks like a frame colour
 *     ("Wood frame" / "Marco de madera" / "Czarny" / "Madeira"). */
function findFrameValue(opts: ShopifySelectedOption[]): string | undefined {
  const direct = findOption(opts, OPTION_FRAME);
  if (direct) return direct;
  const byNameContains = opts.find((o) => FRAME_NAME_RE.test(o.name))?.value;
  if (byNameContains) return byNameContains;
  return opts.find((o) => FRAME_VALUE_RE.test(o.value))?.value;
}

/** Find the variant's size value robustly:
 *  1) by the option named "Size" (any locale alias);
 *  2) failing that, by any option NAME that hits the size keyword regex;
 *  3) failing that, by any option VALUE that looks like a size
 *     ("30x40 cm", "8×10\"", "30 x 40"). */
function findSizeValue(opts: ShopifySelectedOption[]): string | undefined {
  const direct = findOption(opts, OPTION_SIZE);
  if (direct) return direct;
  const byNameContains = opts.find((o) => SIZE_NAME_RE.test(o.name))?.value;
  if (byNameContains) return byNameContains;
  return opts.find((o) => SIZE_VALUE_RE.test(o.value))?.value;
}

/** Find the variant's orientation value robustly. Same pattern as the others. */
function findOrientationValue(opts: ShopifySelectedOption[]): string | undefined {
  const direct = findOption(opts, OPTION_ORIENTATION);
  if (direct) return direct;
  const byNameContains = opts.find((o) => ORIENT_NAME_RE.test(o.name))?.value;
  if (byNameContains) return byNameContains;
  return opts.find((o) => ORIENT_VALUE_RE.test(o.value))?.value;
}

/** Normalise a frame value; empty/missing → "None". */
function normaliseFrame(value: string | undefined): string {
  return value && value.trim() ? value.trim() : "None";
}

/** Combine size + orientation into a single Size axis value. */
function normaliseSize(size: string | undefined, orientation: string | undefined): string {
  const s = (size ?? "").trim();
  const o = (orientation ?? "").trim();
  if (s && o) return `${o} · ${s}`;
  return s || o || "Default";
}

// ---------- Public types ----------

/**
 * Maps every known translated form of a material name (any supported locale)
 * to its canonical English Material value. Lookup is always lower-cased.
 */
const MATERIAL_ALIASES_I18N: Record<string, Material> = {
  // English (canonical)
  "poster": "Poster",
  "framed poster": "Framed Poster",
  "canvas": "Canvas",
  "framed canvas": "Framed Canvas",
  // Gelato / Printful product names that show up verbatim in Shopify catalogs
  // generated by those print-on-demand integrations (uncategorised material
  // names cause variants to fall out of the master grouping).
  "premium matte paper": "Poster",
  "premium matte paper poster": "Poster",
  "enhanced matte paper": "Poster",
  "premium lustre photo paper": "Poster",
  "premium lustre paper": "Poster",
  "semi-glossy poster": "Poster",
  "matte paper": "Poster",
  "stretched canvas": "Canvas",
  "premium stretched canvas": "Canvas",
  "framed premium matte paper": "Framed Poster",
  "framed matte paper": "Framed Poster",
  "framed canvas print": "Framed Canvas",
  "canvas print": "Canvas",
  "print material": "Poster",
  // Spanish
  "póster": "Poster",
  "póster enmarcado": "Framed Poster",
  "lienzo": "Canvas",
  "lienzo enmarcado": "Framed Canvas",
  "papel mate premium": "Poster",
  "lienzo estirado": "Canvas",
  // Portuguese ("papel mate premium" already covered above for Spanish/PT
  // — Portuguese also uses "papel fosco premium")
  "cartaz": "Poster",
  "pôster": "Poster",
  "cartaz emoldurado": "Framed Poster",
  "tela": "Canvas",
  "tela emoldurada": "Framed Canvas",
  "papel fosco premium": "Poster",
  "tela esticada": "Canvas",
  // Polish
  "plakat": "Poster",
  "plakat w ramie": "Framed Poster",
  "płótno": "Canvas",
  "płótno w ramie": "Framed Canvas",
  "papier matowy premium": "Poster",
};

/**
 * Normalise any known material name (in any locale) to a canonical Material.
 * Accepts both the productType field and the title-suffix token.
 */
function normaliseMaterial(raw: string): Material | null {
  return MATERIAL_ALIASES_I18N[raw.trim().toLowerCase()] ?? null;
}

/**
 * Handle suffixes that identify the material portion of a Shopify product
 * handle. Ordered longest-first so "framed-poster" is matched before "poster".
 * Includes English slugs (from products created in English) and localised slugs
 * (from products created in Spanish/Portuguese/Polish).
 */
const HANDLE_MATERIAL_SUFFIXES: Array<{ suffix: string; material: Material }> = [
  // English — canonical
  { suffix: "framed-poster",    material: "Framed Poster" },
  { suffix: "framed-canvas",    material: "Framed Canvas" },
  { suffix: "canvas",           material: "Canvas" },
  { suffix: "poster",           material: "Poster" },
  // English — Gelato / Printful auto-generated names (longest-first ordering
  // is critical here so "framed-premium-matte-paper" matches before
  // "premium-matte-paper").
  { suffix: "framed-premium-matte-paper", material: "Framed Poster" },
  { suffix: "framed-matte-paper",         material: "Framed Poster" },
  { suffix: "premium-matte-paper-poster", material: "Poster" },
  { suffix: "premium-matte-paper",        material: "Poster" },
  { suffix: "premium-lustre-photo-paper", material: "Poster" },
  { suffix: "premium-lustre-paper",       material: "Poster" },
  { suffix: "enhanced-matte-paper",       material: "Poster" },
  { suffix: "semi-glossy-poster",         material: "Poster" },
  { suffix: "matte-paper",                material: "Poster" },
  { suffix: "premium-stretched-canvas",   material: "Canvas" },
  { suffix: "stretched-canvas",           material: "Canvas" },
  { suffix: "canvas-print",               material: "Canvas" },
  { suffix: "framed-canvas-print",        material: "Framed Canvas" },
  // Spanish
  { suffix: "poster-enmarcado", material: "Framed Poster" },
  { suffix: "lienzo-enmarcado", material: "Framed Canvas" },
  { suffix: "lienzo-estirado",  material: "Canvas" },
  { suffix: "lienzo",           material: "Canvas" },
  { suffix: "papel-mate-premium", material: "Poster" },
  { suffix: "póster-enmarcado", material: "Framed Poster" },
  { suffix: "póster",           material: "Poster" },
  // Portuguese
  { suffix: "cartaz-emoldurado",  material: "Framed Poster" },
  { suffix: "tela-emoldurada",    material: "Framed Canvas" },
  { suffix: "tela-esticada",      material: "Canvas" },
  { suffix: "tela",               material: "Canvas" },
  { suffix: "papel-fosco-premium", material: "Poster" },
  { suffix: "cartaz",             material: "Poster" },
  // Polish
  { suffix: "plakat-w-ramie",   material: "Framed Poster" },
  { suffix: "plotno-w-ramie",   material: "Framed Canvas" },
  { suffix: "plotno",           material: "Canvas" },
  { suffix: "papier-matowy-premium", material: "Poster" },
  { suffix: "plakat",           material: "Poster" },
];

/**
 * Extract the painting slug and material from a Shopify product handle.
 * Returns null if no known material suffix is found (→ non-art product).
 *
 * Tolerates Shopify's auto-disambiguation suffix (`-1`, `-2`, …) that gets
 * appended when a duplicate handle is created — these don't mean the product
 * is different, they mean Shopify had to rename it. So
 * "soul-gathering-framed-poster-2" parses identically to
 * "soul-gathering-framed-poster".
 *
 * Example: "double-portrait-pink-framed-poster" → { slug: "double-portrait-pink", material: "Framed Poster" }
 */
function parsePaintingFromHandle(handle: string): { slug: string; material: Material } | null {
  // Strip a trailing "-<digits>" disambiguation suffix before matching.
  const stripped = handle.replace(/-\d+$/, "");
  for (const { suffix, material } of HANDLE_MATERIAL_SUFFIXES) {
    if (stripped.endsWith(`-${suffix}`)) {
      return { slug: stripped.slice(0, -(suffix.length + 1)), material };
    }
  }
  return null;
}

/** Convert a kebab-case slug to Title Case for display.
 *  Example: "double-portrait-on-pink" → "Double Portrait On Pink" */
function titleCaseFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Resolve the canonical painting name + material for a Shopify product.
 *
 * Strategy (priority order):
 *
 * 1. HANDLE + PRODUCTTYPE — locale-independent primary path.
 *    Shopify handles are immutable URL slugs set when the product was created;
 *    they never change with locale. We strip the material suffix from the handle
 *    to get a stable painting slug that is the same for all variants of the same
 *    painting in all languages.
 *    productType is also normalised across locales using MATERIAL_ALIASES_I18N.
 *
 *    This eliminates the core problem: inconsistent Shopify translations across
 *    product variants (e.g. "Retrato doble sobre rosa" vs "Doble retrato sobre
 *    rosa" for the same painting) no longer matter — we never use the title for
 *    the grouping key.
 *
 *    Display name: image-map canonical → English title parse → title-cased slug.
 *
 * 2. IMAGE-MAP + TITLE PARSE — fallback for products without a recognisable
 *    handle suffix (non-art items, custom handles, etc.).
 */
function resolvePainting(product: ShopifyProduct): { painting: string; material: Material } | null {
  const fromImage = PAINTING_MAP[product.handle];
  // parseTitle is locale-aware AND falls back to suffix-style parsing for
  // titles like "Narwa Premium Matte Paper" (no separator).
  const parsed = parseTitle(product.title);

  // ── Primary path: handle suffix carries the material ─────────────────────
  const fromHandle = parsePaintingFromHandle(product.handle);
  const handleMaterial = fromHandle?.material ?? normaliseMaterial(product.productType);

  if (fromHandle && handleMaterial) {
    const paintingName =
      fromImage?.painting
        ? canonicalize(fromImage.painting)
        : parsed?.painting
          ? canonicalize(parsed.painting)
          : canonicalize(titleCaseFromSlug(fromHandle.slug));
    return { painting: paintingName, material: handleMaterial };
  }

  // ── Image-map fallback ───────────────────────────────────────────────────
  if (fromImage?.painting) {
    const fallbackMaterial =
      parsed?.material ??
      normaliseMaterial(product.productType) ??
      "Poster";
    return { painting: canonicalize(fromImage.painting), material: fallbackMaterial };
  }

  // ── Title-only fallback (parseTitle handled it) ──────────────────────────
  if (parsed) {
    return { painting: canonicalize(parsed.painting), material: parsed.material };
  }

  // ── Last-resort fallback: handle has no recognised suffix AND title can't
  //    be parsed, but productType still says it's a print material. Treat the
  //    whole handle as the painting slug. Used by clean handles like "narwa"
  //    (no material in the URL) where productType = "Print Material" or
  //    similar tells us what we're looking at. */
  const productMaterial = normaliseMaterial(product.productType);
  if (productMaterial) {
    return {
      painting: canonicalize(titleCaseFromSlug(product.handle)),
      material: productMaterial,
    };
  }

  return null;
}

/** Returns the virtual master handle for a given source product, or null
 *  if the product isn't an art/painting product. Used by the detail page
 *  to redirect legacy URLs to the new master URL.
 *
 *  When `englishCanonicalMap` is supplied (any non-EN locale render),
 *  the handle uses the EN canonical painting name so master URLs are
 *  identical across locales — i.e. /pt/shop/the-ceremony, never
 *  /pt/shop/a-cerimonia. The bucket key in groupProductsByPainting uses
 *  the same source, so the redirect always lands on a real master. */
export function getMasterHandle(
  product: ShopifyProduct,
  englishCanonicalMap?: EnglishPaintingMap,
): string | null {
  const englishPainting = englishCanonicalMap
    ? lookupEnglishPainting(product, englishCanonicalMap)
    : undefined;
  if (englishPainting) return slugify(englishPainting);
  const resolved = resolvePainting(product);
  return resolved ? slugify(resolved.painting) : null;
}

// ---------- Core grouping ----------

type Bucket = {
  painting: string; // canonical (English where available)
  handle: string;
  sources: { product: ShopifyProduct; material: Material; localPainting: string }[];
};

/**
 * Build a map from Shopify product handle → canonical English painting name,
 * computed from a catalog fetched in the EN locale.
 *
 * Kept (with an unchanged public signature) for backwards compatibility with
 * any caller that hasn't migrated to the EN-as-source flow yet. New shop-page
 * code should fetch the EN catalog directly and pass it as the `products`
 * argument to `groupProductsByPainting`, with a `LocaleOverlay` for
 * translation strings — that path doesn't use this map at all.
 */
export type EnglishPaintingMap = {
  byHandle: Map<string, string>;
  byVariantId: Map<string, string>;
};

export function buildEnglishPaintingMap(
  englishProducts: ShopifyProduct[],
): EnglishPaintingMap {
  const byHandle = new Map<string, string>();
  const byVariantId = new Map<string, string>();
  for (const p of englishProducts) {
    const r = resolvePainting(p);
    if (!r) continue;
    byHandle.set(p.handle, r.painting);
    for (const { node: v } of p.variants.edges) {
      if (v.id) byVariantId.set(v.id, r.painting);
    }
  }
  return { byHandle, byVariantId };
}

/**
 * Locale overlay — a thin index over a Shopify catalog fetched in a non-EN
 * locale. We use the EN catalog for variant STRUCTURE (so every locale sees
 * the same 4 materials × 4 frames × all sizes) but pull the displayed STRINGS
 * from this overlay so titles, frame colour names, and material labels show
 * up in the user's language exactly as Maya translated them in Shopify.
 *
 *   `byHandle`     handle → { title, description, descriptionHtml, productType }
 *                  Used to translate the painting title and the Material
 *                  display value (productType IS the localised material name).
 *
 *   `byVariantId`  variant ID → selectedOptions
 *                  Variant IDs are immutable across Markets, so this is the
 *                  reliable cross-locale linker. Used to translate Frame and
 *                  Size values per-variant.
 */
type LocaleProductInfo = {
  handle: string;
  title: string;
  description: string;
  descriptionHtml: string;
  productType: string;
};

export type LocaleOverlay = {
  /** ISO locale code (e.g. "es", "pt"). Used as the key for the
   *  optionTranslations.ts fallback table when Shopify doesn't have a
   *  translation for a particular SKU. */
  locale: string;
  byHandle: Map<string, LocaleProductInfo>;
  /** variant ID → { handle of the locale product that owns this variant,
   *  selectedOptions in the locale }. Variant IDs are immutable across
   *  Markets, so this is the cross-locale linker that works even when
   *  Shopify's URL translation rewrites the handle. */
  byVariantId: Map<string, { handle: string; selectedOptions: ShopifySelectedOption[] }>;
};

export function buildLocaleOverlay(
  localeProducts: ShopifyProduct[],
  locale: string,
): LocaleOverlay {
  const byHandle = new Map<string, LocaleProductInfo>();
  const byVariantId = new Map<
    string,
    { handle: string; selectedOptions: ShopifySelectedOption[] }
  >();
  for (const p of localeProducts) {
    byHandle.set(p.handle, {
      handle: p.handle,
      title: p.title,
      description: p.description,
      descriptionHtml: p.descriptionHtml,
      productType: p.productType,
    });
    for (const { node: v } of p.variants.edges) {
      if (v.id) byVariantId.set(v.id, { handle: p.handle, selectedOptions: v.selectedOptions });
    }
  }
  return { locale, byHandle, byVariantId };
}

/** Resolve the locale product info for an EN source product, even when
 *  Shopify Markets rewrites handles per locale. Tries handle first, then
 *  walks the EN product's variant IDs to find any matching locale product. */
function resolveLocaleProduct(
  enProduct: ShopifyProduct,
  overlay: LocaleOverlay,
): LocaleProductInfo | undefined {
  const byHandle = overlay.byHandle.get(enProduct.handle);
  if (byHandle) return byHandle;
  for (const { node: v } of enProduct.variants.edges) {
    if (!v.id) continue;
    const link = overlay.byVariantId.get(v.id);
    if (!link) continue;
    const info = overlay.byHandle.get(link.handle);
    if (info) return info;
  }
  return undefined;
}

/** Look up a localised product's canonical English painting name in the dual
 *  map: handle first (fast, exact), then variant-ID overlap as a fallback for
 *  catalogs where Shopify rewrites the handle per locale. */
function lookupEnglishPainting(
  product: ShopifyProduct,
  map: EnglishPaintingMap,
): string | undefined {
  const direct = map.byHandle.get(product.handle);
  if (direct) return direct;
  for (const { node: v } of product.variants.edges) {
    const hit = v.id ? map.byVariantId.get(v.id) : undefined;
    if (hit) return hit;
  }
  return undefined;
}

/**
 * Group products into one master per painting.
 *
 * `englishCanonicalMap` (optional): when supplied, the canonical English
 * painting name for each handle is used as the bucket key — this makes the
 * grouping locale-independent and resilient to inconsistent translations in
 * Shopify (e.g. some PT products translated, some not). The display title on
 * the resulting master is still the localised painting name (parsed from the
 * locale-fetched product title); only the BUCKETING uses the English key.
 */
export function groupProductsByPainting(
  products: ShopifyProduct[],
  englishCanonicalMap?: EnglishPaintingMap,
  localeOverlay?: LocaleOverlay,
): ShopifyProduct[] {
  const buckets = new Map<string, Bucket>();
  const passthrough: ShopifyProduct[] = [];

  for (const product of products) {
    const resolved = resolvePainting(product);
    // Even if local resolution fails, an English-map hit can still bucket the
    // product (e.g. PT title is so mangled we can't parse, but the EN catalog
    // told us this handle = "Soul Gathering"). Try handle first, then fall
    // back to variant-ID overlap for catalogs where Shopify Markets rewrites
    // handles per locale.
    const englishPainting = englishCanonicalMap
      ? lookupEnglishPainting(product, englishCanonicalMap)
      : undefined;
    if (!resolved && !englishPainting) {
      passthrough.push(product);
      continue;
    }

    // Bucket key: ALWAYS prefer the English canonical name (immutable across
    // locales). Falls back to the locally-resolved name when no map is given
    // (e.g. the EN locale itself, or a product missing from the map).
    const canonicalPainting = englishPainting ?? resolved!.painting;
    const handle = slugify(canonicalPainting);

    // Material: trust local resolution; if absent (English-map-only path),
    // try product.productType, default to Poster.
    const material =
      resolved?.material ?? normaliseMaterial(product.productType) ?? "Poster";

    // localPainting: the painting name as it appears in THIS locale's source
    // product (used later to pick the best display title for the master).
    const localPainting = resolved?.painting ?? canonicalPainting;

    let bucket = buckets.get(handle);
    if (!bucket) {
      bucket = { painting: canonicalPainting, handle, sources: [] };
      buckets.set(handle, bucket);
    }
    bucket.sources.push({ product, material, localPainting });
  }

  const masters = Array.from(buckets.values()).map((b) =>
    buildMasterProduct(b, localeOverlay),
  );
  return [...masters, ...passthrough];
}

function buildMasterProduct(
  bucket: Bucket,
  localeOverlay?: LocaleOverlay,
): ShopifyProduct {
  // Pick the Framed Poster source as the description/SEO template.
  const template =
    bucket.sources.find((s) => s.material === "Framed Poster")?.product ??
    bucket.sources[0].product;

  // Locale used as the lookup key for the optionTranslations.ts fallback
  // table. translateOptionValue silently passes through unknown locales, so
  // an empty string here means "don't translate" (the EN/PL behaviour).
  const overlayLocale = localeOverlay?.locale ?? "";

  /** Look up the locale-translated string for an EN material name. Tries (in
   *  order): the source product's productType in the overlay (Shopify's own
   *  translation, e.g. "Cartaz Emoldurado"), then the optionTranslations
   *  fallback. Returns the canonical English when neither yields anything. */
  const localizedMaterialName = (m: Material): string => {
    if (!localeOverlay) return m;
    // Find a source product carrying this material and look up the locale's
    // productType, which IS the translated material label.
    for (const src of bucket.sources) {
      if (src.material !== m) continue;
      const localeInfo = resolveLocaleProduct(src.product, localeOverlay);
      const pt = localeInfo?.productType?.trim();
      if (pt) return pt;
    }
    return translateOptionValue("Material", m, overlayLocale) || m;
  };

  /** Pull the locale-translated frame/size value for a given EN variant.
   *  Variant IDs are immutable across Markets, so byVariantId is reliable. */
  const localizedVariantOption = (
    enVariant: ShopifyProductVariant,
    axis: typeof OPTION_FRAME | typeof OPTION_SIZE | typeof OPTION_ORIENTATION,
  ): string | undefined => {
    if (!localeOverlay) return undefined;
    const link = localeOverlay.byVariantId.get(enVariant.id);
    if (!link) return undefined;
    if (axis === OPTION_FRAME) return findFrameValue(link.selectedOptions);
    if (axis === OPTION_SIZE) return findSizeValue(link.selectedOptions);
    return findOrientationValue(link.selectedOptions);
  };

  // Collect ONE hero image per source product (so the gallery is a tight set
  // of ~4 — Poster / Framed Poster / Canvas / Framed Canvas — instead of every
  // mockup variant). Per-frame and per-size images are still attached to each
  // variant via `variant.image` and surface when the user picks that variant.
  // We start with the template (Framed Poster) so it's the leading thumbnail.
  const images: ShopifyImage[] = [];
  const seenImageUrls = new Set<string>();
  const pushImage = (img: ShopifyImage | null | undefined) => {
    if (!img || !img.url || seenImageUrls.has(img.url)) return;
    seenImageUrls.add(img.url);
    images.push(img);
  };
  const orderedSources = [
    ...bucket.sources.filter((s) => s.product === template),
    ...bucket.sources.filter((s) => s.product !== template),
  ];
  for (const { product } of orderedSources) {
    pushImage(product.images.edges[0]?.node);
  }

  // Collect & remap variants. Dedup by (Material, Frame, Size); first wins.
  const variants: ShopifyProductVariant[] = [];
  const seenVariantKeys = new Set<string>();
  let minPrice = Number.POSITIVE_INFINITY;
  let maxPrice = Number.NEGATIVE_INFINITY;
  let currencyCode = "EUR";

  // Match values that indicate the product ships UNASSEMBLED / DIY-kit form,
  // in any supported locale. Used as a NEGATIVE filter: by default we keep
  // every framed variant; we only drop ones explicitly flagged as kit. The
  // old code did the opposite (kept only values literally equal to
  // "ready-to-hang"), which silently nuked entire Framed Poster catalogs on
  // ES/PT/PL where the value is "Listo para colgar" / "Pronto para pendurar"
  // / "Gotowe do powieszenia".
  const NOT_ASSEMBLED_RE =
    /not\s*assembled|kit|para\s*montar|sin\s*montar|por\s*montar|a\s*montar|nieskręcony|nieskrecony|do\s*złożenia|do\s*zlozenia|do\s*samodzielnego/i;

  for (const { product, material } of bucket.sources) {
    for (const { node: v } of product.variants.edges) {
      // Drop unassembled variants for any framed material (Poster or Canvas).
      // Localised: keep variants by default unless the Assembly value
      // explicitly indicates kit / not-assembled.
      if (material === "Framed Poster" || material === "Framed Canvas") {
        const assembly = findOption(v.selectedOptions, OPTION_ASSEMBLY);
        if (assembly && NOT_ASSEMBLED_RE.test(assembly)) continue;
      }

      // Read raw frame/size/orientation FIRST from the EN variant (the
      // structure source-of-truth). When a localeOverlay is present, prefer
      // the translated value for the same variant ID — that's Shopify's own
      // translation. If Shopify hasn't translated this SKU yet, fall through
      // to the optionTranslations.ts table so the UI never mixes English
      // with localised labels.
      const enFrame = findFrameValue(v.selectedOptions);
      const enSize = findSizeValue(v.selectedOptions);
      const enOrientation = findOrientationValue(v.selectedOptions);

      const overlayFrame = localizedVariantOption(v, OPTION_FRAME);
      const overlaySize = localizedVariantOption(v, OPTION_SIZE);
      const overlayOrientation = localizedVariantOption(v, OPTION_ORIENTATION);

      const fallbackFrame = enFrame
        ? translateOptionValue("Frame", enFrame, overlayLocale)
        : enFrame;
      // Sizes are universal (cm/inches) — translateOptionValue passes through.
      const fallbackSize = enSize;
      const fallbackOrientation = enOrientation;

      const sourceFrame = overlayFrame ?? fallbackFrame;
      const sourceSize = overlaySize ?? fallbackSize;
      const sourceOrientation = overlayOrientation ?? fallbackOrientation;

      const frame =
        material === "Poster" || material === "Canvas" ? "None" : normaliseFrame(sourceFrame);
      const size = normaliseSize(sourceSize, sourceOrientation);

      // Dedup key uses the EN material name + EN-derived frame/size so
      // identical structural variants don't double up just because one was
      // matched via locale overlay and another via fallback.
      const enFrameNormalised =
        material === "Poster" || material === "Canvas" ? "None" : normaliseFrame(enFrame);
      const enSizeNormalised = normaliseSize(enSize, enOrientation);
      const key = `${material}|${enFrameNormalised}|${enSizeNormalised}`;
      if (seenVariantKeys.has(key)) continue;
      seenVariantKeys.add(key);

      const price = Number(v.price.amount);
      if (Number.isFinite(price)) {
        if (price < minPrice) minPrice = price;
        if (price > maxPrice) maxPrice = price;
      }
      currencyCode = v.price.currencyCode || currencyCode;

      const materialDisplay = localizedMaterialName(material);

      variants.push({
        id: v.id, // KEEP real Shopify variant id — checkout depends on it.
        title: `${materialDisplay} / ${frame} / ${size}`,
        price: v.price,
        availableForSale: v.availableForSale,
        image: v.image ?? null,
        selectedOptions: [
          { name: OUT_MATERIAL, value: materialDisplay },
          { name: OUT_FRAME, value: frame },
          { name: OUT_SIZE, value: size },
        ],
      });
    }
  }

  // Sort variants for stable, sensible rendering: Framed Poster first (the
  // master view), then Framed Canvas, Canvas, Poster; within each, by Frame
  // then Size. Build a label→canonical map so localised material strings
  // (e.g. "Póster enmarcado") still sort by their canonical position.
  const materialOrder: Record<Material, number> = {
    "Framed Poster": 0,
    "Framed Canvas": 1,
    Canvas: 2,
    Poster: 3,
  };
  const orderByLabel = new Map<string, number>();
  for (const m of MATERIALS) orderByLabel.set(localizedMaterialName(m), materialOrder[m]);
  variants.sort((a, b) => {
    const ma = orderByLabel.get(a.selectedOptions[0].value) ?? 99;
    const mb = orderByLabel.get(b.selectedOptions[0].value) ?? 99;
    if (ma !== mb) return ma - mb;
    if (a.selectedOptions[1].value !== b.selectedOptions[1].value) {
      return a.selectedOptions[1].value.localeCompare(b.selectedOptions[1].value);
    }
    return a.selectedOptions[2].value.localeCompare(b.selectedOptions[2].value);
  });

  if (!Number.isFinite(minPrice)) minPrice = 0;
  if (!Number.isFinite(maxPrice)) maxPrice = minPrice;

  // Union of tags + a `palette:bw|color` tag for sidebar filtering.
  const tagSet = new Set<string>();
  for (const { product } of bucket.sources) for (const t of product.tags) tagSet.add(t);
  const palette = getPaintingPalette(bucket.painting);
  if (palette) tagSet.add(`${PALETTE_TAG_PREFIX}${palette}`);

  const availableForSale = variants.some((v) => v.availableForSale);

  // Per-material descriptions: each Shopify source product carries its own
  // copy (Poster paper specs, Canvas specs, etc.) The detail page swaps to
  // the right one when the buyer changes Material.
  //
  // Keyed by the LOCALISED material display name (because that's what the
  // detail page now sees as `selectedOptions["Material"]`). Description text
  // itself prefers the locale overlay's translation when present, falling
  // back to the EN source product's description.
  const materialDescriptions: Record<
    string,
    { description: string; descriptionHtml: string }
  > = {};
  for (const { product, material } of bucket.sources) {
    const key = localizedMaterialName(material);
    if (materialDescriptions[key]) continue;
    const localeData = localeOverlay
      ? resolveLocaleProduct(product, localeOverlay)
      : undefined;
    materialDescriptions[key] = {
      description: localeData?.description || product.description,
      descriptionHtml: localeData?.descriptionHtml || product.descriptionHtml,
    };
  }

  // Display title: prefer Shopify's localised title for any of the bucket's
  // source products (read via the locale overlay). Parses out the
  // " — Material" suffix when present so the master shows just the painting
  // name, not "Painting — Material". Falls back to the canonical English
  // painting name when there's no overlay or no translation hit.
  let displayTitle = bucket.painting;
  if (localeOverlay) {
    for (const src of [template, ...bucket.sources.map((s) => s.product)]) {
      const localeData = resolveLocaleProduct(src, localeOverlay);
      if (!localeData?.title) continue;
      const parsed = parseTitle(localeData.title);
      const candidate = parsed?.painting?.trim() || localeData.title.trim();
      if (candidate && candidate !== bucket.painting) {
        displayTitle = candidate;
        break;
      }
    }
  } else {
    // No overlay: keep the original "any source has a localPainting that
    // differs from the canonical" heuristic so EN-only and PL-as-EN flows
    // are unchanged.
    const translatedSource = bucket.sources.find(
      (s) => s.localPainting && s.localPainting !== bucket.painting,
    );
    if (translatedSource) displayTitle = translatedSource.localPainting;
  }

  // Pick the locale-translated description for the master itself, preferring
  // the template (Framed Poster) source's translation.
  const templateLocale = localeOverlay
    ? resolveLocaleProduct(template, localeOverlay)
    : undefined;
  const masterDescription = templateLocale?.description || template.description;
  const masterDescriptionHtml = templateLocale?.descriptionHtml || template.descriptionHtml;

  return {
    id: `virtual:${bucket.handle}`,
    title: displayTitle,
    handle: bucket.handle,
    description: masterDescription,
    descriptionHtml: masterDescriptionHtml,
    images: { edges: images.map((node) => ({ node })) },
    priceRange: {
      minVariantPrice: { amount: minPrice.toFixed(2), currencyCode },
      maxVariantPrice: { amount: maxPrice.toFixed(2), currencyCode },
    },
    variants: { edges: variants.map((node) => ({ node })) },
    tags: Array.from(tagSet),
    productType: template.productType || "Painting",
    availableForSale,
    materialDescriptions,
  };
}
